// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.3.0.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides in ThisBuild ++= Set(
  "com.github.mpilquist" % "simulacrum_2.11" % "0.8.0",
  "org.scala-sbt" % "test-interface" % "1.0",
  "org.scalacheck" % "scalacheck_2.11" % "1.12.5",
  "org.scalaz" % "scalaz-concurrent_2.11" % "7.2.6",
  "org.scalaz" % "scalaz-core_2.11" % "7.2.6",
  "org.scalaz" % "scalaz-effect_2.11" % "7.2.6",
  "org.typelevel" % "catalysts-macros_2.11" % "0.0.2",
  "org.typelevel" % "catalysts-platform_2.11" % "0.0.2",
  "org.typelevel" % "cats-core_2.11" % "0.7.2",
  "org.typelevel" % "cats-free_2.11" % "0.7.2",
  "org.typelevel" % "cats-jvm_2.11" % "0.7.2",
  "org.typelevel" % "cats-kernel-laws_2.11" % "0.7.2",
  "org.typelevel" % "cats-kernel_2.11" % "0.7.2",
  "org.typelevel" % "cats-laws_2.11" % "0.7.2",
  "org.typelevel" % "cats-macros_2.11" % "0.7.2",
  "org.typelevel" % "cats_2.11" % "0.7.2",
  "org.typelevel" % "discipline_2.11" % "0.4",
  "org.typelevel" % "machinist_2.11" % "0.4.1",
  "org.typelevel" % "macro-compat_2.11" % "1.1.1"
)
// LIBRARY_DEPENDENCIES_HASH c2c7de4735f001d57522a999031905160542ec3d
