// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.3.0.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides in ThisBuild ++= Set(

)
// LIBRARY_DEPENDENCIES_HASH 73a4bed2ffa6e67f73ecf32ffe675fbbd60a2057
